# Changes here will be overwritten by Copier
_commit: v2.1.13
_src_path: harmon-stack
ansible: true
bunch_add: true
ci_cd: github_actions
code_templates: false
data_folder: false
design_files: false
devcontainer: false
git_init: false
github_collaboration_templates: true
github_release_init: false
github_remote_create: false
infra: []
license: mit
observability: []
obsidian_project_add: false
project_description: project description test wind
project_name: Test Wind
project_slug: test-wind
project_type: code
project_url: https://test-wind.com
run_task_bootstrap: false
run_task_install: false
